// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package bootstrap

import (
	"github.com/weplanx/openapi/api"
	"github.com/weplanx/openapi/api/geo"
	"github.com/weplanx/openapi/api/index"
	"github.com/weplanx/openapi/common"
)

// Injectors from wire.go:

func NewAPI() (*api.API, error) {
	values, err := LoadValues()
	if err != nil {
		return nil, err
	}
	client, err := UseMongoDB(values)
	if err != nil {
		return nil, err
	}
	database := UseDatabase(client, values)
	inject := &common.Inject{
		Values: values,
		Mongo:  client,
		Db:     database,
	}
	hertz, err := UseHertz(values)
	if err != nil {
		return nil, err
	}
	service := &index.Service{
		Inject: inject,
	}
	controller := &index.Controller{
		IndexService: service,
	}
	geoService := &geo.Service{
		Inject: inject,
	}
	geoController := &geo.Controller{
		Service: geoService,
	}
	apiAPI := &api.API{
		Inject:          inject,
		Hertz:           hertz,
		IndexController: controller,
		IndexService:    service,
		GeoController:   geoController,
		GeoService:      geoService,
	}
	return apiAPI, nil
}
