// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
	"openapi/app"
	"openapi/app/index"
	"openapi/common"
)

// Injectors from wire.go:

func App(value *common.Values) (*gin.Engine, error) {
	inject := &common.Inject{
		Values: value,
	}
	service := &index.Service{
		Inject: inject,
	}
	controller := &index.Controller{
		Service: service,
	}
	engine := app.New(value, controller)
	return engine, nil
}
