// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
	"github.com/weplanx/openapi/app"
	"github.com/weplanx/openapi/app/geo"
	"github.com/weplanx/openapi/app/index"
	"github.com/weplanx/openapi/bootstrap"
	"github.com/weplanx/openapi/common"
)

// Injectors from wire.go:

func App(value *common.Values) (*gin.Engine, error) {
	client, err := bootstrap.UseMongoDB(value)
	if err != nil {
		return nil, err
	}
	database := bootstrap.UseDatabase(client, value)
	inject := &common.Inject{
		Values:      value,
		MongoClient: client,
		Db:          database,
	}
	service := &index.Service{
		Inject: inject,
	}
	controller := &index.Controller{
		Service: service,
	}
	geoService := &geo.Service{
		Inject: inject,
	}
	geoController := &geo.Controller{
		Service: geoService,
	}
	engine := app.New(value, controller, geoController)
	return engine, nil
}
